version: '3'
services:
  main-postgresql:
    image: 'postgres:14.3-alpine'
    container_name: cleverDbApi
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TITLE}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  news-api:
    container_name: News-api
    profiles:
      - dev
    ports:
      - "8080:8081"
    build:
      context: /api
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-postgresql:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB_TITLE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - main-postgresql
      - user-service
  user-service:
    container_name: User-microservice
    ports:
      - "8081:8080"
    build:
      context: /user-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-postgresql:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB_TITLE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - main-postgresql