version: '3.8'

services:
  main-api:
    image: 'postgres:14.3-alpine'
    container_name: cleverDbApi
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TITLE}