server:
  port: 8080

spring:
  profiles:
    active: lfu
  data:
    redis:
      port: 6379
  cache:
    lfu:
      max-entries:
        size: 120
#    type: redis
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123123
    username: cleverMan
    url: jdbc:postgresql://localhost:5430/cleverDbApi
  liquibase:
    enabled: true
    change-log: db.migration/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org:
      springframework:
        transaction: debug
        orm:
          jpa: debug
