server:
  port: 8080

spring:
  cache:
    lru:
      max-entries:
        size: 120
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123123
    username: cleverMan
    url: jdbc:postgresql://localhost:5430/cleverDbApi
  liquibase:
    enabled: true
    change-log: db.migration/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: lru
