server:
  port: 8082
spring:
  profiles:
    active:
      - dev
app:
  token:
    expire-time: 40000
  clients:
    user:
      client-name: userClient
      url: 127.0.0.1:8081
      client-path: /api/v1/users
  cache:
    type: REDIS
    size: 120