create table roles
(
    id   integer generated by default as identity (start with 2)
        primary key,
    role varchar(20) not null
);


create table users
(
    id       bigint generated by default as identity (start with 2)
        primary key,
    password varchar(255) not null,
    username varchar(100) not null,
    role_id  integer
        constraint fk_role_id
            references roles
);