create table news
(
    id            bigint generated by default as identity (start with 2)
        primary key,
    news_title    varchar(50)  not null,
    creation_date date         not null,
    text          varchar(255) not null,
    author_name   varchar(120) not null
);

create table comments
(
    id            bigint generated by default as identity (start with 2)
        primary key,
    creation_date date         not null,
    text          varchar(255) not null,
    author_name   varchar(40)  not null,
    news_id       bigint
        constraint fk_news_id
            references news
);